name: Metube
version: 0.1.0
slug: metube
url: https://github.com/alexta69/metube/
init: false
description: Metube is web front end to yt-dlp
webui: http://[HOST]:[PORT:8081]
stage: experimental
arch:
- aarch64
- amd64
ports:
  8081/tcp: 8081
image: ghcr.io/alexta69/metube
